### PR TITLE
Soft delete application details

### PR DESCRIPTION
**Pull request by cbordier**
Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Soft delete application

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

### CODE REVIEW

**Comment by docsbuilder** [comment]
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 74af3cc |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-286.amplify-central.opendocs-builder.pcloud.axway.int |

**Review by lbadenhop — APPROVED** [review]

**Comment by lbadenhop** [comment]
@cbordier Please approve my edits before I merge. Thanks.

**Comment by lbadenhop** [comment]
@cbordier  MarkdownChecks is working now, but I haven't updated the linters in the project yet.

**Comment by cbordier** [comment]
@lbadenhop I approve the updates.

**Pull request merged**
