### PR TITLE
Test escaping pipe in code blocks

### PR DESCRIPTION
**Pull request by jquick-axway**
Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

**Do NOT Merge!**
This is a test.

## Checklist for contributors

Before submitting this PR, please make sure:

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

### CODE REVIEW

**Comment by cbordier** [comment]
@jquick-axway I think your test1 is the best option.

**Comment by jquick-axway** [comment]
I did some digging. Hugo uses "goldmark" to process markdown.
https://gohugo.io/news/0.60.0-relnotes/

Goldmark used to have this "exact" bug... and it's been fixed.
https://github.com/yuin/goldmark/issues/164
https://github.com/yuin/goldmark/commit/036c8738df354cb23006064e1820f978af2ba042

We need to update our Hugo version to get the newest goldmark version.
https://github.com/gohugoio/hugo/releases

I've updated `HUGO_VERSION` in this PR, but it doesn't seem to work. We also specify `HUGO_VERSION` in the "axway-open-docs-common" subrepo as well... and I'm not sure if I need to change it there too and how I can test it out. Hmm...
https://github.com/Axway/amplify-central/pull/61/commits/f9efa1b56616bb1fcc3a8ffa0d1e9ba0fb5f51af

**Comment by lbadenhop** [comment]
@jquick-axway Please go with the workaround (option 1, as Cyrille suggested) until a technical resource can investigate how an update will impact the docs and how Zoomin processes those changes. We can readdress this issue once we have the answers.

**Comment by lbadenhop** [comment]
Closing this issue. We can readdress when a technical resource can investigate how an update will impact the docs.

**Pull request closed without merging**
