### PR TITLE
Add content to Publish to Marketplace

### PR DESCRIPTION
**Pull request by lbadenhop**
Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Add content from NBC doc, sections 5.7.1, 5.7.2. 

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

### CODE REVIEW

**Comment by lbadenhop** [comment]
@cbordier Which options are correct: Private and Public or Protected and Public? Marketplace Settings page reflects Protected and Public, NBC doc reflects Private and Public.

**Review by georgiana-caras — COMMENTED** [review]
This content is cannot be published yet as the feature will not become available until mid-June to end of June and the experience might shape up differently. Content will be updated shortly.

**Review by cbordier — APPROVED** [review]
I approve the changes

**Review by georgiana-caras — COMMENTED** [review]
Looks good

**Pull request merged**
