### PR TITLE
Apigov 27623   update service details with runtime compliance grading

### PR DESCRIPTION
**Pull request by ColeSammonsAxway**
Update public docs for Service Details/List

### CODE REVIEW

**Comment by docsbuilder** [comment]
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | d5ea153 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-450.amplify-central.opendocs-builder.pcloud.axway.int |

**Review by robertengaxway — APPROVED** [review]
approved

**Review by robertengaxway — APPROVED** [review]
approved

**Review by lbadenhop — APPROVED** [review]

**Review by robertengaxway — APPROVED** [review]
Looks good

**Pull request merged**
