### PR TITLE
APIGOV-26703 - duplicate plan

### PR DESCRIPTION
**Pull request by cbordier**
Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Add the duplicate product plan action and explanation

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

### CODE REVIEW

**Comment by docsbuilder** [comment]
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 0a8c2c3 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-447.amplify-central.opendocs-builder.pcloud.axway.int |

**Comment by cbordier** [comment]
@lbadenhop that is ready for your review.

**Comment by lbadenhop** [comment]
@cbordier please approve my edits.

**Comment by cbordier** [comment]
@lbadenhop I approve the changes you made.

**Review by lbadenhop — APPROVED** [review]

**Pull request merged**
