### PR TITLE
API Server Resources explained and webhook flow

### PR DESCRIPTION
**Pull request by DesertLeprechaun**
Added additional information on API Server Resources and the fields available
Clarified webhook creation flow (webhook + trigger)

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

### CODE REVIEW

**Comment by cbordier** [comment]
@DesertLeprechaun , I formatted some pieces and corrected the markdown issues.
You can have a look to the commit I did in Commit tab section
Please review before we can merge.

**Review by DesertLeprechaun — COMMENTED** [review]
Looks good. Thanks Cyrille

**Review by cbordier — APPROVED** [review]
Changes approved
@lbadenhop, you can merge

**Review by lbadenhop — APPROVED** [review]

**Comment by lbadenhop** [comment]
@cbordier Please review my edits.

**Pull request merged**
