### PR TITLE
APIGOV-25123 Document Marketplace customizable footer

### PR DESCRIPTION
**Pull request by lbadenhop**
Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

### CODE REVIEW

**Comment by docsbuilder** [comment]
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 943d2a2 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-278.amplify-central.opendocs-builder.pcloud.axway.int |

**Comment by lbadenhop** [comment]
@cbordier, one question I have is whether the colors for the links, text, and background follow what is set in Marketplace appearance, or are they preset generic colors. I not sure if this is something that needed to be documented? 
The content is ready for your review.

**Comment by cbordier** [comment]
@lbadenhop the link follow the theme link color:
image

**Review by cbordier — APPROVED** [review]
@lbadenhop I approve the changes

**Comment by lbadenhop** [comment]
@Cyrille Does the color theme need to be mentioned?

**Pull request merged**
