### PR TITLE
APIGOV-28662 - add in entra id reference

### PR DESCRIPTION
**Pull request by sbolosan**
Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

### CODE REVIEW

**Comment by docsbuilder** [comment]
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | d0565f3 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-562.amplify-central.opendocs-builder.pcloud.axway.int |

**Review by robertengaxway — APPROVED** [review]
I approve but do not publish until we release Azure v1.3.6.  We have not released it yet

**Review by lbadenhop — APPROVED** [review]

**Comment by sbolosan** [comment]
It is draft for that reason @robertengaxway , also, if I can get @vivekschauhan to look at it and make sure there isn't another reference we want to put in the docs. Thnx

**Comment by cbordier** [comment]
@sbolosan I think we need to update that page too: https://docs.axway.com/bundle/amplify-central/page/docs/connect_manage_environ/index.html#on-premise-agent-features to indicate we support Entra ID in credential type

**Comment by sbolosan** [comment]
Yup, good catch @cbordier , will do!

**Pull request merged**
