### PR TITLE
Marketplace internationalization

### PR DESCRIPTION
**Pull request by cbordier**
Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Add the product localization: Marketplace settings / Product i18n

## Deploy preview link

Settings:
http://pr-525.amplify-central.opendocs-builder.pcloud.axway.int/docs/manage_marketplace/customize_marketplace/marketplace_localization/
Product:
http://pr-525.amplify-central.opendocs-builder.pcloud.axway.int/docs/manage_product_foundry/foundry_localization/
Document library:
http://pr-525.amplify-central.opendocs-builder.pcloud.axway.int/docs/manage_document_library/documentation_library_management/#multi-languages
Category:
http://pr-525.amplify-central.opendocs-builder.pcloud.axway.int/docs/manage_product_foundry/foundry_product_tags_attributes_categories/#multi-languages
Stage:
http://pr-525.amplify-central.opendocs-builder.pcloud.axway.int/docs/connect_manage_environ/stage/#multi-languages
API/CLI:
http://pr-525.amplify-central.opendocs-builder.pcloud.axway.int/docs/integrate_with_central/api_server/#multi-languages-support
ARD/SRD/CRD:
http://pr-525.amplify-central.opendocs-builder.pcloud.axway.int/docs/integrate_with_central/customize_ard_crd/#localize-the-screen-customization
e2e:
http://pr-525.amplify-central.opendocs-builder.pcloud.axway.int/docs/integrate_with_central/samples/sample_start_to_end/

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

### CODE REVIEW

**Comment by docsbuilder** [comment]
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | a0e8515 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-525.amplify-central.opendocs-builder.pcloud.axway.int |

**Review by lbadenhop — APPROVED** [review]

**Comment by lbadenhop** [comment]
@cbordier, I'm not done reviewing, but accidentally clicked the approval.

**Comment by cbordier** [comment]
@lbadenhop - Dev will deploy the feature next Monday (10/10). We would need to deploy right after (Monday evening).

**Comment by lbadenhop** [comment]
@cbordier Do you know why my latest commits aren't showing up in Deploy Preview?

**Comment by lbadenhop** [comment]
@cbordier, Wing has fixed the issue. The commits are now being built

**Comment by cbordier** [comment]
@lbadenhop I approve the changes.

**Pull request merged**
