### PR TITLE
Billing integration precision after the Monthly demo

### PR DESCRIPTION
**Pull request by cbordier**
Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

add the yaml object description
Typo for subscription_id and subscription_invoice_id

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

### CODE REVIEW

**Comment by docsbuilder** [comment]
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 62f6dd2 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-448.amplify-central.opendocs-builder.pcloud.axway.int |

**Comment by cbordier** [comment]
@lbadenhop that one is ready too for your review.

**Review by lbadenhop — APPROVED** [review]

**Comment by lbadenhop** [comment]
@cbordier, does Robert need to review before I merge?

**Comment by cbordier** [comment]
@lbadenhop @robertengaxway can have a quick look but the changes are straightforward.

**Comment by lbadenhop** [comment]
@cbordier, I'll merge now without Robert's review. I only asked because he was listed as a reviewer.

**Pull request merged**
