### PR TITLE
APIGOV-25823: Add CLI docs for API linting/compliance

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
https://jira.axway.com/browse/APIGOV-25823

**Replaces Pull Request:**
https://github.com/Axway/amplify-central/pull/306

**Summary:**
Documents Amplify Central's API Compliance and linting feature and how to work with it via the "axway central" CLI.

### CODE REVIEW

**Comment by docsbuilder** [comment]
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | dbfac6d |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-323.amplify-central.opendocs-builder.pcloud.axway.int |

**Comment by jquick-axway** [comment]
@lbadenhop, @robertengaxway, I wasn't able to make changes to branch https://github.com/Axway/amplify-central/pull/306 . This is a branch of that branch with the changes you want. Can we finish the review here please? Thanks.

**Review by robertengaxway — APPROVED** [review]
Thank you Josh, the example look great

**Comment by jquick-axway** [comment]
@lbadenhop , can I get your review/approval for this doc change too please? Thanks.

**Comment by lbadenhop** [comment]
@jquick-axway - Yes. I'll review/merge/upload tomorrow. Thanks!

**Review by lbadenhop — APPROVED** [review]

**Pull request merged**
