### PR TITLE
Update region information

### PR DESCRIPTION
**Pull request by lbadenhop**
Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Besides your intended changes, please add these additional region changes. Issue opened @ https://github.com/Axway/amplify-central/issues/422. 

    Currently, most of the pages referencing the Central URL are using the US one. But since we added multiple regions EU/APAC, it is not clear which URL should be used.

    Problem locations:

    * https://docs.axway.com/bundle/amplify-central/page/docs/integrate_with_central/platform-auth-examples/index.html
    * https://docs.axway.com/bundle/amplify-central/page/docs/integrate_with_central/query-the-traceability-apis-with-lexus/index.html
    * https://docs.axway.com/bundle/amplify-central/page/docs/integrate_with_central/cli_central/index.html (need to mention the --region parameter)

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

### CODE REVIEW

**Comment by docsbuilder** [comment]
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | b4ff263 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-408.amplify-central.opendocs-builder.pcloud.axway.int |

**Comment by lbadenhop** [comment]
@robertengaxway, I made minor edits to the three topics that need the region URLS. See the PR description for additional changes that are needed in these topics.

**Review by robertengaxway — APPROVED** [review]
approved

**Review by cbordier — APPROVED** [review]
I approve the changes

**Comment by lbadenhop** [comment]
@cbordier Are you now able to close out https://github.com/Axway/amplify-central/issues/422?

**Pull request merged**
