### PR TITLE
APIGV-27675 - Custom billing integration

### PR DESCRIPTION
**Pull request by cbordier**
Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Add the custom billing integration topic to help customer build their own,

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

### CODE REVIEW

**Comment by docsbuilder** [comment]
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | a2fbdcd |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-433.amplify-central.opendocs-builder.pcloud.axway.int |

**Comment by cbordier** [comment]
@lbadenhop you can start having a look.
I will tell you once the dev push the feature.

**Comment by cbordier** [comment]
@lbadenhop it is ready for your review.

**Comment by cbordier** [comment]
I approved Lisa's changes

**Comment by lbadenhop** [comment]
@cbordier do you approve the changes?

**Review by lbadenhop — APPROVED** [review]

**Pull request merged**
