### PR TITLE
APIGOV-26192 - Updates for Agent IDP configuration

### PR DESCRIPTION
**Pull request by vivekschauhan**
- Added new configuration for agent to setup OAuth IdP provider for marketplace provisioning

Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

### CODE REVIEW

**Comment by docsbuilder** [comment]
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 16803ca |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-346.amplify-central.opendocs-builder.pcloud.axway.int |

**Comment by robertengaxway** [comment]
Content is good, can we consider making it easier for our customers to find by moving the section up just after "Build an Agent with SKD" at the same section level.

**Comment by cbordier** [comment]
@robertengaxway, I like the idea of moving this doc a level up.
@lbadenhop, we could also add an extra page under Manage your Marketplace (Provisioning Marketplace credentials) that point to this page so that it is easier to find...
@lbadenhop, if there are keywords we could have to help the search, maybe this is something to add too.

**Comment by lbadenhop** [comment]
Creating another PR to creating new page and move content.

**Pull request merged**
