### PR TITLE
Add best practices section

### PR DESCRIPTION
**Pull request by lbadenhop**
Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Add Best practices section that includes the using_teams_amplify_platform.md
https://deploy-preview-54--amplify-central.netlify.app/docs/best_practices/using_teams_amplify_platform/

## Checklist for contributors

Before submitting this PR, please make sure:

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

### CODE REVIEW

**Comment by lbadenhop** [comment]
@jdelbarre-axway Please review.

**Review by cbordier — APPROVED** [review]
I approve the changes

**Comment by lbadenhop** [comment]
@jdelbarre-axway Please add a comment when you are done editing/reviewing. Otherwise, I won't know you are finished. Thanks.

**Comment by jdelbarre-axway** [comment]
Is it possible to have a better resolution for the diagrams? I attached the two images
Best Practices_001
Best Practices_002

**Comment by lbadenhop** [comment]
@jdelbarre-axway The images have been fixed. Please let me know when you are done reviewing so I can merge.

**Pull request merged**
