### PR TITLE
Webhook content

### PR DESCRIPTION
**Pull request by lbadenhop**
Thank you for your contribution to the Amplify-Central repo.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

### CODE REVIEW

**Comment by lbadenhop** [comment]
@cbordier Can you please review this PR request before I add other reviewers. I will send Dave's email to you again so you'll have access to the files he changed/added. You'll notice that he included the integrate_with_central/cli_central folder that includes many cli files. I can't tell what files have changed, so I started going through the files line by line until I discovered that several cli files we had set to draft: yes to hide are not set to draft: yes in his folder (build_an_asset_using_the_axway_central_cli.md, cli_apiservices.md, cli_create_fetch_resources.md, cli_register_api.md). He also added two new files, but the "Date modified" in his directory are from March (cli_asset_catalog.md, cli_product_foundry.md). Maybe you understand what he has done?

**Comment by lbadenhop** [comment]
@cbordier Ready for your review. please ignore cli_register_api.md and build_an_asset_using_the_axway_central_cli.md in this PR--they are marked "draft" and will not display in Netlify or the portal. Also, I will create another PR where I make the existing cli pages follow the same tutorial format as the two new cli pages in this PR (steps outlining the processes instead of bullets).

**Comment by cbordier** [comment]
@lbadenhop, there is an issue with content/en/docs/integrate_with_central/webhook/unified_catalog_webhook.md
Lg 136 and Lg 151 reference json file that are hosted on  https://amplify-central.netlify.app/samples/... i think it should be /samples/...

**Comment by lbadenhop** [comment]
@cbordier Updated the path. Let me know when I can add Bas as a reviewer.

**Review by cbordier — APPROVED** [review]
I approve the changes

**Comment by cbordier** [comment]
@lbadenhop it looks good for me to add Bas.

**Comment by lbadenhop** [comment]
@cbordier Bas does not have a github account. Any suggestions on how he can review? Maybe I merge? If so, it could be uploaded to production if any changes are published. I have one PR waiting for review / merge / upload (which I will do today).

**Pull request merged**
